export const CART_ADD_ITEM = "CART_ADD_ITEM";
export const CART_REMOVE_ITEM = "CART_REMOVE_ITEM";


export const CART_SAVE_SHIPPINGADDRESS = "CART_SAVE_SHIPPINGADRESS"

export const CART_SAVE_PAYMENTMETHOD = "CART_SAVE_PAYMENTMETHOD"